name: build

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        working-directory: ./Team-3749-2022
        run: chmod +x ./gradlew

      - name: Build with Gradle
        working-directory: ./Team-3749-2022
        run: ./gradlew build
